language: go

go:
  - 1.13
  - master

notifications:
  email: false

addons:
  sonarcloud:
    organization: "negapedia"
    token:
      secure: "5bc4e215cd8c7f8dd81bfddd858fc41756abb379"

script:
  - go test -race ./... -coverprofile=coverage.out
  - sonar-scanner