dist: trusty

language: go

go:
  - 1.13
  - master

notifications:
  email: false

addons:
  sonarcloud:
    organization: "negapedia"
    token:
      secure: "RqAoOD/c8qz1xlqZI4qp6NI26jZNbZZwk+aXK0hUogU+kc4ztUXC8y7NpKerhyhJRFdfUOOnWKkivTdG3QT5rMQ1F8WwIgUi5kJsuCgQB7hKZBD3G9ygzChwS9W6CfECPWn8NVYnX8uwlM+mp75YezjgIauJoVvpEElgVs/7VRkY9WJia4hgpZfqi+SQe4InaLD01Ac+mmfAp0hkDeUHFHIDIou3RNnmgkFD9IFySgrAWv1blVYsYDU7/Dyj4Kr4t7uN+gshxpJsADzwtD/NKr5v+ShhdgYuqOYNC+U0bZOiKoNwLh0ELqe2As6HWkJmO7y21rsxQWTkNAQNHND2PEjmunQZ1mufdM38Z/Jz8mm6Wv3if+g8ryfbBqEp7hHX/8EfT9JTs8bTdRLv5rh9KT3Zd9scY9LZxFiK4uj59aiL/MntTS2c6nSRs2IOYDzzUwiVGLiHjmNghJla7n1hsKUiai1XQfILS0AmOwlYLmud7UFZ3dnIx3cgbjZEHhu8A2bVWrtSl1pq3RQYworD3Q12XlzD9tYIgmEVi4GLwdTd3MWzbAB4M0QfLnIlEvzHh84+GXmi7z4czA2xqpdTKBikzxUo5f6VnKEJXT9VBsURrJNWlDgu+Z6ApBDANd9PM8RtWdagyoASbvExQi0rMdIL1TADSwPtkYTDNp76NVk="

script:
  - go test -race ./... -coverprofile=coverage.out
  - sonar-scanner -Dsonar.projectKey=negapedia_wikipage -Dsonar.projectName=wikipage -Dsonar.projectVersion=1.0 -Dsonar.sources=. -Dsonar.tests=. -Dsonar.test.inclusions=**/*_test.go -Dsonar.go.coverage.reportPaths=coverage.out